data:
  fasta_path: data/human_chr1_4096_filtered.fa

model:
  D: 1024                  # embedding dimension
  K: 16                    # local window size
  local_encoder_layers: 2
  latent_encoder_layers: 4
  latent_decoder_layers: 2
  local_decoder_layers: 1
  num_heads: 1

training:
  batch_size: 8
  num_epochs: 10
  val_split: 0.1
  num_workers: 16
  lr: 0.0001
  device: cuda             # set to "cuda" for GPU
